if [ $PC == laptop ]; then
    picom -b --config ~/.config/picom/picom-laptop.conf
else
    nvidia-settings -l --config="$HOME/.config/nvidia/settings"
fi

chbg $HOME/.config/back.png &

exec awesome --no-argb
