general {{
    col.active_border = rgb({color2.strip})
    col.inactive_border = rgb({background.strip})
    col.group_border = rgb({background.strip})
    col.group_border_active = rgb({color2.strip})
}}
