#!/usr/bin/env bash

echo $(tail -n 1 ~/.cache/volume.cache) > ~/.cache/volume.cache
echo $(tail -n 1 ~/.cache/brightness.cache) > ~/.cache/brightness.cache

hc() {
    herbstclient "$@"
}

hc emit_hook reload

source $HOME/.config/herbstluftwm/theme.sh
source $HOME/.config/herbstluftwm/binds.sh

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
hc rule index=e # prefer placing clients in an empty frame

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule title='Steam Settings' floating=on
hc rule class~'(popterm|Nemo|Typora)' floating=on

hc set snap_distance 12
hc set snap_gap 4
hc set tree_style '╾│ ├└╼─┐'
hc set update_dragged_clients on
hc set focus_follows_mouse on

# unlock, just to be sure
hc unlock

hc detect_monitors
