#!/bin/dash

swww init &
chbg ~/.config/back.png &

eww daemon; eww open bar &

# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# sleep 1
# killall xdg-desktop-portal-hyprland
# killall xdg-desktop-portal-wlr
# killall xdg-desktop-portal
# /usr/lib/xdg-desktop-portal-hyprland &
# sleep 2
# /usr/lib/xdg-desktop-portal &
