#!/bin/dash

unclutter --timeout 3 &

swww init &
chbg ~/.config/back.png &

eww daemon; eww open bar &

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

sleep 4
killall xdg-desktop-portal-hyprland; killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 4
/usr/lib/xdg-desktop-portal &

