#!/bin/dash
AMOUNT=5

case $1 in
    up)
        light -A $AMOUNT
        icon=" "
        ;;
    down)
        light -U $AMOUNT
        icon=" "
        ;;
    min)
        light -S 1
        icon=" "
        ;;
    max)
        light -S 100
        icon=" "
        ;;
esac

light=$(light)
notify-send -r 2 "$icon" "${light%\.*}"
