#!/bin/zsh

case $1 in
    -l)
        file="$2"
        light="-l"
        ;;
    *)
        file="$1"
        light=""
        ;;
esac

swww img --transition-fps 60 --transition-type "grow" --transition-pos 1720,1000 --transition-duration 1.5 $file &
wal -c; wal -e -s -t $light -i "$file"
cp $file ~/.config/back.png

xrdb ~/.cache/wal/Xresources
kill -SIGUSR1 $(pidof st)
hyprctl reload
eww reload
