#!/bin/bash

workspaces() {
focused="$(bspc query --names -D -d .focused)"
occufocused="$(bspc query --names -D -d .occupied; bspc query --names -D -d .focused)"
desktops="$(cat <<<$occufocused | sort | uniq)"

if [ $(echo "$desktops" | head -n1) = "0" ] && [ $(echo "$desktops" | wc -l) -gt 1 ]; then
    desktops="$(cat <<<$desktops | sed '1{H;d}; ${p;x;s/^\n//}')"
fi

desktops="$(cat <<<$desktops | sed 's/'$focused'//')"

echo -n '(box :class "workspaces" :halign "center" :orientation "v" :spacing 15'
for desktop in $desktops; do
    echo -n '(label :text "'$desktop'")'
done
echo ')'
}

workspaces
bspc subscribe desktop node_transfer | while read -r _; do
workspaces
done
