#!/bin/dash
AMOUNT=5

case $1 in
    up)
        light -A $AMOUNT
        notify-send -r 2 " " "$(light | awk -F '.' '{print $1}')%"
        ;;
    down)
        light -U $AMOUNT
        notify-send -r 2 " " "$(light | awk -F '.' '{print $1}')%"
        ;;
    min)
        light -S 1
        notify-send -r 2 " " "$(light | awk -F '.' '{print $1}')%"
        ;;
    max)
        light -S 100
        notify-send -r 2 " " "$(light | awk -F '.' '{print $1}')%"
        ;;
esac
