#!/bin/dash

icon="$(cat ~/.scripts/font-awesome-icons | wofi --show dmenu | cut -d ' ' -f1)"

if [ "$icon" = "" ]; then
    exit 1
fi

echo $icon | xclip -r -sel clip
notify-send "Emoji copied to clipboard" "$icon"
