if [ $PC == laptop ]; then
    # picom -b --config ~/.config/picom/picom-laptop.conf
    eww daemon; eww open bar
else
    nvidia-settings -l --config="$HOME/.config/NVIDIA/settings"
    eww daemon; eww open-many bar0 bar1

    killall -e xdg-desktop-portal-gtk
    killall xdg-desktop-portal
    /usr/lib/xdg-desktop-portal-gtk &
    sleep 2
    /usr/lib/xdg-desktop-portal &
fi

dunst &

chbg $HOME/.config/back.png &

exec herbstluftwm --no-transparency
