if [ $PC == laptop ]; then
    # picom -b --config ~/.config/picom/picom-laptop.conf
    echo
else
    nvidia-settings -l --config="$HOME/.config/NVIDIA/settings"
fi

chbg -l $HOME/.config/back.png &

exec awesome --no-argb
